### ISSUE TITLE
Problem initializing plugin: kontalk:jabber:iq:register

### ISSUE THREAD

**Issue by thecodeflash** [kontalk/tigase-kontalk#10]
Hello Sir/Madam,

I am trying to deploy Kontalk server on my machine and want to use Nexmo for verification. I configured the server as per the guidelines, specifying API key, Access Token and Providers. 

But when I started the server and tried connecting to it, I got an error saying verification error. When I looked at logs of the server I found error which is like this:

```
SessionManager.setProperties()     SEVERE:   Problem initializing plugin: kontalk:jabber:iq:register
tigase.db.TigaseDBException: No providers configured
        at org.kontalk.xmppserver.KontalkIqRegister.init(KontalkIqRegister.java:133)
        at tigase.server.xmppsession.SessionManager.setProperties(SessionManager.java:922)
        at tigase.conf.ConfiguratorAbstract.setup(ConfiguratorAbstract.java:516)
        at tigase.conf.ConfiguratorAbstract.componentAdded(ConfiguratorAbstract.java:152)
        at tigase.conf.Configurator.componentAdded(Configurator.java:50)
        at tigase.conf.Configurator.componentAdded(Configurator.java:33)
        at tigase.server.AbstractComponentRegistrator.addComponent(AbstractComponentRegistrator.java:116)
        at tigase.server.MessageRouter.addComponent(MessageRouter.java:108)
        at tigase.server.MessageRouter.addRouter(MessageRouter.java:145)
        at tigase.server.MessageRouter.setProperties(MessageRouter.java:698)
        at tigase.conf.ConfiguratorAbstract.setup(ConfiguratorAbstract.java:516)
        at tigase.conf.ConfiguratorAbstract.componentAdded(ConfiguratorAbstract.java:152)
        at tigase.conf.Configurator.componentAdded(Configurator.java:50)
        at tigase.conf.Configurator.componentAdded(Configurator.java:33)
        at tigase.server.AbstractComponentRegistrator.addComponent(AbstractComponentRegistrator.java:116)
        at tigase.server.MessageRouter.addRegistrator(MessageRouter.java:131)
        at tigase.server.MessageRouter.setConfig(MessageRouter.java:597)
        at tigase.server.XMPPServer.start(XMPPServer.java:142)
        at tigase.server.XMPPServer.main(XMPPServer.java:112)
```

I am attaching my log and configuration files as well.
[init.properties.txt](https://github.com/kontalk/tigase-kontalk/files/626445/init.properties.txt)
[tigase.conf.txt](https://github.com/kontalk/tigase-kontalk/files/626446/tigase.conf.txt)
[tigase.log.0.txt](https://github.com/kontalk/tigase-kontalk/files/626444/tigase.log.0.txt)
[tigase-console.log.txt](https://github.com/kontalk/tigase-kontalk/files/626447/tigase-console.log.txt)

Thank You.

Hope to see your response soon.

Regards,
Vishwajeet Srivastava

**Comment by daniele-athome** [comment]
Hello, we recently changed registration provider configuration syntax to support multiple providers:
https://github.com/kontalk/tigase-kontalk/blob/master/etc/init.properties

Here is an extract for the Android provider:

```
# Registration provider configuration
# Android emulator registration provider: it will emulate an SMS with the verification code
sess-man/plugins-conf/kontalk\:jabber\:iq\:register/providers[s]=android=org.kontalk.xmppserver.registration.AndroidEmulatorProvider
# how many seconds to wait before a user can retry registration
sess-man/plugins-conf/kontalk\:jabber\:iq\:register/android-expire[I]=900
# the sender number of the emulated SMS
sess-man/plugins-conf/kontalk\:jabber\:iq\:register/android-sender=12345
# the device ID of the emulator to send the SMS to
sess-man/plugins-conf/kontalk\:jabber\:iq\:register/android-device=emulator-5554
```

**Comment by thecodeflash** [comment]
Hello Sir,

But I want to use Nexmo for SMS verification purpose. I followed the steps to use Nexmo from here [https://github.com/kontalk/tigase-kontalk/blob/master/docs/local-server-howto.md#registration](url) . 

Please point out and help me in what I did wrong on server deployment. 

Thank You

**Comment by thecodeflash** [comment]
Hello Sir,

I have made the changes as mentioned by you (Sorry for earlier reply). but Now I am getting this new error 

`2016-12-02 15:27:12.425 [main]             SessionManager.setProperties()     SEVERE:   Problem initializing plugin: kontalk:jabber:iq:register
tigase.db.TigaseDBException: Bad provider definition: org.kontalk.xmppserver.registration.NexmoVerifyProvider
        at org.kontalk.xmppserver.KontalkIqRegister.init(KontalkIqRegister.java:141)
        at tigase.server.xmppsession.SessionManager.setProperties(SessionManager.java:922)
        at tigase.conf.ConfiguratorAbstract.setup(ConfiguratorAbstract.java:516)
        at tigase.conf.ConfiguratorAbstract.componentAdded(ConfiguratorAbstract.java:152)
        at tigase.conf.Configurator.componentAdded(Configurator.java:50)
        at tigase.conf.Configurator.componentAdded(Configurator.java:33)
        at tigase.server.AbstractComponentRegistrator.addComponent(AbstractComponentRegistrator.java:116)
        at tigase.server.MessageRouter.addComponent(MessageRouter.java:108)
        at tigase.server.MessageRouter.addRouter(MessageRouter.java:145)
        at tigase.server.MessageRouter.setProperties(MessageRouter.java:698)
        at tigase.conf.ConfiguratorAbstract.setup(ConfiguratorAbstract.java:516)
        at tigase.conf.ConfiguratorAbstract.componentAdded(ConfiguratorAbstract.java:152)
        at tigase.conf.Configurator.componentAdded(Configurator.java:50)
        at tigase.conf.Configurator.componentAdded(Configurator.java:33)
        at tigase.server.AbstractComponentRegistrator.addComponent(AbstractComponentRegistrator.java:116)
        at tigase.server.MessageRouter.addRegistrator(MessageRouter.java:131)
        at tigase.server.MessageRouter.setConfig(MessageRouter.java:597)
        at tigase.server.XMPPServer.start(XMPPServer.java:142)
        at tigase.server.XMPPServer.main(XMPPServer.java:112)
Loading plugin: kontalk:jabber:iq:roster=4:1165 ...     , version: 7.1.0-SNAPSHOT-b39/f54cd663 (2016-11-28/06:57:30)
`.

**Comment by daniele-athome** [comment]
I just noticed this:

```
sess-man/plugins-conf/kontalk\:jabber\:iq\:register/brand=ChattyCash
```

And I found [your app on the Play Store](https://play.google.com/store/apps/details?id=com.berdie.chattycash), clearly a fork of Kontalk. If you don't publish your source code you'll be in violation of GPL terms.
