### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by asgharkhare2016** [kontalk/tigase-kontalk#9]
hi I tried to install kontalk server using the [how to guide](https://github.com/kontalk/tigase-kontalk/blob/master/docs/local-server-howto.md) but the database preparation phase doesn't succeed, 
when I tried to initialize database with `./scripts/db-create-derby.sh /var/lib/tigase/derby  `  this error has occurred: 
```
./scripts/db-create-derby.sh /var/lib/tigase/derby

...

tigase.util.DBSchemaLoader       getResource             FINEST     Getting resource: derby-schema--dbName-schema @ filename: /opt/kontalk/kontalk/tigase-server/database/derby-schema--dbName-schema.sql
Exception in thread "main" java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at tigase.util.DBSchemaLoader.loadSQLQueries(DBSchemaLoader.java:363)
        at tigase.util.DBSchemaLoader.loadSchemaQueries(DBSchemaLoader.java:431)
        at tigase.util.DBSchemaLoader.validateDBSchema(DBSchemaLoader.java:653)
        at tigase.util.DBSchemaLoader$Tasks$3.execute(DBSchemaLoader.java:1010)
        at tigase.util.DBSchemaLoader.execute(DBSchemaLoader.java:212)
        at tigase.util.DBSchemaLoader.main(DBSchemaLoader.java:190)
LogLevel: ALL
...

```
what should I do to solve this problem?
thanks.

**Comment by daniele-athome** [comment]
I'm sorry but Kontalk currently requires a MySQL (or compatible) database server. Derby won't work.
